### ISSUE TITLE
Add docs for enhancing security

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/serverless-chat-langchainjs#34]
Currently this sample is designed to be as easy as possible to work one and deploy.
If deployed in an enterprise context, we usually enforce tighter security rules and we want to explain what can be changed in the sample to improve its security:

#### Tasks
- [x] Create a new docs "Enhance security" in /`docs/enhance-security.md` that explains how to:
    - [ ] ~~Disable exporting keys in output (and also the ability to work locally)~~
    - [x] Configure vnet (and optionally make the app only available on internal network)
    - [ ] ~~Use Azure Key Vault for key and connection string storage~~

**Comment by sinedied** [comment]
Partially replaced by #56
